#!/usr/bin/env python3
"""Phase 4: absolute energy calibration against an external SRAM model (CACTI 7).

Everything else in validation/ checks the model against ITSELF -- hand identities, A/B isolation,
containment. The three external references (SCALE-Sim, Gemmini RTL, Eyeriss silicon) validate
LATENCY and TRAFFIC. Nothing validated absolute ENERGY against anything outside the repo, which is
why RE2 refuses to call any shipped config's totals absolute picojoules and refuses it a wattage.

This gate closes that for the on-chip SRAM, which is where most of the energy is. The reference is
generated by CACTI 7 for the geometry each config DECLARES -- not fitted to make the model agree --
and validation/phase4/PROVENANCE.md records the tool commit, the base config and every override.

THE FINDING. The shipped gemmini.cfg energies are not reproducible from its own declared geometry,
in two ways that need no assumption about the technology node:
  * its GLB input and weight buffers are both declared 128 KB, yet priced 3.06 and 1.07 pJ per
    access -- a 2.9x gap two arrays of identical capacity cannot have;
  * its 64 B weight local buffer is priced 0.44 pJ against 0.18 for the 512 B input buffer, so the
    SMALLER array costs 2.4x more per access, which no SRAM model produces.
Those numbers therefore encode something other than array geometry -- plausibly per-datatype
activity factors, or a different unit convention. They are left exactly as they are: they may come
from post-layout Gemmini data this repository does not contain. What this gate does is pin the
inconsistency so it stays visible and cannot be quietly reconciled by editing either side.

NOT COVERED: the NoP link energy (the RE6 contract) still has no external reference. Simba
(MICRO 2019) is the right one and is paywalled; PROVENANCE.md lists exactly which figures would
close it. No remembered number was written into the reference.

Checks (asserted; non-zero exit on failure):
  P4-1 The calibrated fixture's declared SRAM costs are EXACTLY the CACTI reference rows for its
       geometry, so the calibration cannot drift away from its source.
  P4-2 GEOMETRY CONSISTENCY, on the calibrated fixture: buffers of equal declared capacity cost the
       same per access, and a smaller buffer never costs more than a larger one. Both follow from
       any SRAM model and neither depends on the node.
  P4-3 The SHIPPED gemmini.cfg violates P4-2, with the exact figures recorded here. This check
       FAILS if the violation disappears -- not because the violation is desirable, but because its
       disappearance means either the config was changed without updating this record, or the
       checker stopped looking.
  P4-4 RE2/E20-1 END TO END, and note the direction. gemmini_cacti22's SRAM and DRAM costs ARE
       externally derived, but its MAC, accumulator, cast and control costs are not -- and E20-1
       makes an unpriced active event disqualify a wattage. So the fixture is REFUSED power, and
       that is the correct outcome, not a regression: it is what the earlier version got wrong when
       it reported 418.685 mW with its setup, accumulator and cast events at 0.00 pJ. What this
       check pins is that the refusal happens for the right reason (an undercounted numerator, not
       a missing unit or an uncalibrated precision) and that the total says ESTIMATED. The positive
       wattage path lives in validation/power and validation/unpriced, on a fixture that is complete
       rather than partly external.
  P4-5 The reference itself is sane: energy falls monotonically with the technology node
       (45 > 32 > 22 nm) for every geometry, and a larger array costs more at a fixed node.

THE DRAM ARM. CACTI does not model DRAM, so the off-chip term was left uncalibrated by the SRAM
work above. DRAMsim3 -- already vendored at ext/DRAMsim3 -- carries JEDEC device files with the
datasheet IDD currents and computes per-command energy from them, which makes it a legitimate
reference for exactly the devices the NPUsim configs NAME in `dram_config`.

  P4-10 NVDLA (2026-08-26): nvdla_small_cacti22's declared SRAM costs are exactly the
       CACTI rows for the RTL macro geometries -- CBUF bank reads/writes at the 64 b
       access for in/out and 8x that for the 512 b weight line (8 banks in parallel);
       the per-byte accumulator key equals the mean of the CACC row's read/write
       divided by its 16 B access; the [dram] beat cost equals the DDR3-1600 row's
       per-byte figure x 8 B. Wattage must be REFUSED (MAC and control unpriced) and
       the total must say ESTIMATED -- the same direction P4-4 pins for gemmini.
  P4-6 The DRAM reference is INDEPENDENTLY re-derived, not just copied out of the tool: for each
       DDR3/DDR4 device the per-burst read energy is recomputed here from that device file's own
       VDD, IDD4R, IDD3N, BL, bus width, device width and tCK, and must equal the CSV. Plus the
       reference must be ordered sanely -- the stacked HBM2 interface below every DDR part.
  P4-7 The calibrated fixture's DRAM energy is exactly the reference row for the device IT names,
       scaled by its own transaction width.
  P4-8 DEVICE INDEPENDENCE, recorded: the shipped configs declare the same 64 pJ per DRAM
       transaction across devices whose per-byte energy differs more than 4x (HBM2 12.56 vs
       DDR3-1600 56.53 pJ/byte). Like P4-3 this FAILS if it disappears, because its disappearance
       means the configs changed without this record being updated.
  P4-9 ... and the contrast that makes P4-8 precise: within gemmini_dram_detail the DRAM TIMING *is*
       derived from the named device to the cycle -- t_ras_cycle = 7 is exactly 28 tCK x 1.25 ns
       over the 5 ns model clock -- while its energy is not derived from it at all. So the gap is
       not "nobody looked at the datasheet"; it is that only the timing came from there.
       (`dram_config` cannot resolve this either way: it is read only under -DDRAMSIM3, and
       npusim.sh builds with DRAMSIM3=0, so the device name has no effect on any validated run.)
"""
import csv
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import perturb_lib as pl                                            # noqa: E402

HERE = Path(__file__).resolve().parent
REFERENCE = HERE / "cacti_sram_reference.csv"
DRAM_REFERENCE = HERE / "dramsim3_dram_reference.csv"
DRAM_DEVICE_FILES = Path(__file__).resolve().parents[2] / "ext" / "DRAMsim3" / "configs"
CALIBRATED_DEVICE = "DDR3_8Gb_x16_1600"
MODEL_CLOCK_NS = 5.0        # 200 MHz, the frequency every fixture declares
CALIBRATED, SHIPPED = "gemmini_cacti22", "gemmini"
WORKLOAD, MAPPING = "gemm_64x64x64", "ws"
NODE = 22
LEAK_PJ_PER_CYCLE = 5.0     # 200 MHz -> 5 ns per cycle; pJ/cycle = mW * 5

# Which reference row backs each (section, key, datatype slot) of the calibrated fixture.
BINDINGS = (
    ("systolic_array", "lb_read_energy",  ("pe_local_buffer_input", "pe_local_buffer_weight",
                                           "pe_local_buffer_output"), "read_pJ_per_access"),
    ("systolic_array", "lb_write_energy", ("pe_local_buffer_input", "pe_local_buffer_weight",
                                           "pe_local_buffer_output"), "write_pJ_per_access"),
    ("separate",       "read_energy",     ("glb_input_128KB", "glb_weight_128KB",
                                           "glb_output_64KB"), "read_pJ_per_access"),
    ("separate",       "write_energy",    ("glb_input_128KB", "glb_weight_128KB",
                                           "glb_output_64KB"), "write_pJ_per_access"),
    ("multi_chip",     "read_energy",     ("multi_chip_256KB",)*3, "read_pJ_per_access"),
    ("multi_chip",     "write_energy",    ("multi_chip_256KB",)*3, "write_pJ_per_access"),
)
# (section, size key or literal capacities, cost key) triples whose geometry must be consistent.
# A section may name its capacities either way (`*_size` or `*_buffer`); try both, and require at
# least one arm per section to resolve so a renamed key cannot silently skip the check.
GEOMETRY = (("systolic_array", (("input_size", "weight_size", "output_size"),
                                ("input_buffer", "weight_buffer", "output_buffer")),
             ("lb_read_energy", "lb_write_energy")),
            ("separate", (("input_size", "weight_size", "output_size"),),
             ("read_energy", "write_energy")))
SLOTS = ("input", "weight", "output")


def section_text(target, section):
    text = (pl.ACCELERATORS / f"{target}.cfg").read_text(encoding="utf-8")
    start = text.index(f"[{section}]")
    rest = [text.index(f"[{s}]") for s in re.findall(r"^\[([a-z_]+)\]", text, re.M)
            if text.index(f"[{s}]") > start]
    return text[start:min(rest)] if rest else text[start:]


def declared(target, section, key):
    found = re.search(rf"^{re.escape(key)}\s*=\s*(\S+)", section_text(target, section), re.M)
    if not found:
        return None
    return [float(f) for f in found.group(1).split(":")]


def main() -> int:
    failures = []
    if not REFERENCE.exists():
        raise SystemExit(f"missing CACTI reference: {REFERENCE}")
    rows = {(r["component"], int(r["tech_nm"])): r for r in csv.DictReader(open(REFERENCE))}

    # P4-1
    for section, key, components, field in BINDINGS:
        values = declared(CALIBRATED, section, key)
        if values is None:
            failures.append(f"P4-1 {section}.{key} is not declared in {CALIBRATED}")
            continue
        for slot, component, value in zip(SLOTS, components, values):
            expected = float(rows[(component, NODE)][field])
            if abs(value - expected) > 5e-4:
                failures.append(f"P4-1 {section}.{key}[{slot}]: declares {value} but CACTI gives "
                                f"{expected} for {component} at {NODE} nm; the fixture has drifted "
                                f"from its reference")

    # P4-2 / P4-3
    def geometry_violations(target):
        found = []
        for section, size_key_sets, cost_keys in GEOMETRY:
            sizes = None
            for size_keys in size_key_sets:
                candidate = [declared(target, section, k) for k in size_keys]
                if all(c is not None for c in candidate):
                    sizes = [c[0] for c in candidate]
                    break
            if sizes is None:
                found.append(f"{section}: no capacity keys resolved (tried "
                             f"{[list(k) for k in size_key_sets]}), so its geometry is UNCHECKED")
                continue
            for cost_key in cost_keys:
                costs = declared(target, section, cost_key)
                if costs is None:
                    continue
                for i in range(len(sizes)):
                    for j in range(len(sizes)):
                        if i >= j:
                            continue
                        if sizes[i] == sizes[j] and abs(costs[i] - costs[j]) > 1e-9:
                            found.append(f"{section}.{cost_key}: {SLOTS[i]} and {SLOTS[j]} are both "
                                         f"{sizes[i]} yet cost {costs[i]} and {costs[j]} "
                                         f"({max(costs[i], costs[j])/min(costs[i], costs[j]):.2f}x)")
                        elif sizes[i] > sizes[j] and costs[i] < costs[j] - 1e-9:
                            found.append(f"{section}.{cost_key}: {SLOTS[j]} is smaller "
                                         f"({sizes[j]} vs {sizes[i]}) yet costs MORE "
                                         f"({costs[j]} vs {costs[i]})")
        return found

    for bad in geometry_violations(CALIBRATED):
        failures.append(f"P4-2 {CALIBRATED}: {bad}. A CACTI-derived fixture must be geometrically "
                        f"consistent by construction")
    shipped_violations = geometry_violations(SHIPPED)
    if not shipped_violations:
        failures.append(f"P4-3 {SHIPPED} no longer violates geometry consistency. Either the config "
                        f"changed without updating this gate's recorded finding, or the check "
                        f"stopped looking -- see the module docstring")

    # P4-4
    def energy_report(target):
        text = pl.run(target, WORKLOAD, MAPPING)
        if text is None:
            raise SystemExit(f"{target} does not run")
        summary = text.split("Energy summary", 1)[1].split("MAC result", 1)[0]
        power = re.search(r"Average total power\s*:\s*([\d.]+) mW", summary)
        return {
            "unit_note": re.search(r"Energy unit\s*:(.*)", summary).group(1).strip(),
            "estimated": "ESTIMATED" in re.search(r"Layer total energy\s*:(.*)",
                                                  summary).group(1),
            "power_mW": float(power.group(1)) if power else None,
            "unsupported": "unsupported" in summary,
        }

    calibrated = energy_report(CALIBRATED)
    shipped = energy_report(SHIPPED)
    if calibrated["power_mW"] is not None:
        failures.append(f"P4-4 {CALIBRATED}: reports {calibrated['power_mW']} mW although its MAC, "
                        f"accumulator, cast and control costs are not calibrated -- E20-1 requires "
                        f"an unpriced active event to disqualify a wattage")
    if not calibrated["estimated"]:
        failures.append(f"P4-4 {CALIBRATED}: its total is not marked ESTIMATED even though several "
                        f"active events fire unpriced")
    if "UNDERCOUNT" not in calibrated["unit_note"] and "undercount" not in calibrated["unit_note"]:
        # the refusal must be for the numerator, not for a missing unit or an uncalibrated precision
        note = re.search(r"Average power\s*:(.*)", pl.run(CALIBRATED, WORKLOAD, MAPPING)).group(1)
        if "UNDERCOUNT" not in note:
            failures.append(f"P4-4 {CALIBRATED}: refused for the wrong reason ({note.strip()}); its "
                            f"unit and precision ARE declared, so the refusal must name the "
                            f"undercounted numerator")
    if shipped["power_mW"] is not None:
        failures.append(f"P4-4 {SHIPPED}: reports {shipped['power_mW']} mW without any external "
                        f"calibration; RE2 must refuse it")
    if not shipped["estimated"]:
        failures.append(f"P4-4 {SHIPPED}: its total is not marked ESTIMATED")

    # P4-5
    components = sorted({component for component, _ in rows})
    for component in components:
        nodes = sorted({node for c, node in rows if c == component}, reverse=True)
        for field in ("read_pJ_per_access", "write_pJ_per_access"):
            series = [float(rows[(component, n)][field]) for n in nodes]
            for coarse, fine in zip(series, series[1:]):
                if fine >= coarse:
                    failures.append(f"P4-5 {component} {field}: {fine} at the finer node is not "
                                    f"below {coarse} at the coarser one ({nodes}); the reference "
                                    f"itself is not sane")
    glb_big = float(rows[("glb_input_128KB", NODE)]["read_pJ_per_access"])
    glb_small = float(rows[("glb_output_64KB", NODE)]["read_pJ_per_access"])
    if glb_small >= glb_big:
        failures.append(f"P4-5: the 64 KB array ({glb_small}) is not cheaper than the 128 KB one "
                        f"({glb_big}) at {NODE} nm")

    # ---- DRAM arm (P4-6 .. P4-9) -------------------------------------------------------------
    if not DRAM_REFERENCE.exists():
        raise SystemExit(f"missing DRAMsim3 reference: {DRAM_REFERENCE}")
    dram_ref = {r["device"]: r for r in csv.DictReader(open(DRAM_REFERENCE))}

    def device_param(device, key):
        text = (DRAM_DEVICE_FILES / f"{device}.ini").read_text(encoding="utf-8")
        found = re.search(rf"^{key}\s*=\s*([\d.]+)", text, re.M)
        return float(found.group(1)) if found else None

    # P4-6 -- independent re-derivation of the JEDEC read energy, for the DDR parts whose
    # burst_cycle is BL/2 (DDR3 and DDR4; the stacked and low-power parts use other divisors).
    rederived = 0
    for device in sorted(dram_ref):
        if not device.startswith(("DDR3", "DDR4")):
            continue
        vdd = device_param(device, "VDD")
        idd4r, idd3n = device_param(device, "IDD4R"), device_param(device, "IDD3N")
        bl, bus, dev_w = (device_param(device, "BL"), device_param(device, "bus_width"),
                          device_param(device, "device_width"))
        tck = device_param(device, "tCK")
        if None in (vdd, idd4r, idd3n, bl, bus, dev_w, tck):
            failures.append(f"P4-6 {device}: its device file is missing a power or organization "
                            f"parameter, so the reference cannot be re-derived")
            continue
        expected = vdd*(idd4r - idd3n)*(bl/2)*(bus/dev_w)*tck
        reported = float(dram_ref[device]["read_pJ_per_burst"])
        if abs(reported - expected) > 0.5:
            failures.append(f"P4-6 {device}: the reference says {reported} pJ per read burst but the "
                            f"device file's own JEDEC parameters give {expected:.2f} "
                            f"(VDD {vdd} x (IDD4R {idd4r} - IDD3N {idd3n}) x BL/2 {bl/2} x "
                            f"{bus/dev_w:.0f} devices x tCK {tck})")
        else:
            rederived += 1
    if rederived < 4:
        failures.append(f"P4-6: only {rederived} device(s) were independently re-derived; the "
                        f"reference is then largely unchecked")
    stacked = [float(r["read_pJ_per_byte"]) for d, r in dram_ref.items() if d.startswith("HBM")]
    ddr = [float(r["read_pJ_per_byte"]) for d, r in dram_ref.items() if d.startswith(("DDR", "LPDDR"))]
    if stacked and ddr and max(stacked) >= min(ddr):
        failures.append(f"P4-6: the stacked interface ({max(stacked)} pJ/byte) is not below every "
                        f"DDR part ({min(ddr)} pJ/byte); the reference ordering is not sane")

    # P4-7 / P4-8 -- declared DRAM energy vs the device each config names
    def dram_declaration(target):
        text = (pl.ACCELERATORS / f"{target}.cfg").read_text(encoding="utf-8")
        device = re.search(r"^dram_config\s*=\s*\S*?([A-Za-z0-9_]+)\.ini", text, re.M)
        block = section_text(target, "dram")
        width = re.search(r"^bitwidth\s*=\s*(\d+)", block, re.M)
        energy = re.search(r"^read_energy\s*=\s*([\d.]+)", block, re.M)
        if not (device and width and energy):
            return None
        return {"device": device.group(1), "bytes_per_txn": int(width.group(1))//8,
                "pJ_per_txn": float(energy.group(1))}

    calibrated_dram = dram_declaration(CALIBRATED)
    if calibrated_dram is None:
        failures.append(f"P4-7 {CALIBRATED}: no DRAM device/energy declaration to check")
    else:
        if calibrated_dram["device"] != CALIBRATED_DEVICE:
            failures.append(f"P4-7 {CALIBRATED} names {calibrated_dram['device']} but this gate "
                            f"calibrates against {CALIBRATED_DEVICE}")
        else:
            expected = (float(dram_ref[CALIBRATED_DEVICE]["read_pJ_per_byte"])
                        * calibrated_dram["bytes_per_txn"])
            if abs(calibrated_dram["pJ_per_txn"] - expected) > 0.01:
                failures.append(f"P4-7 {CALIBRATED}: declares {calibrated_dram['pJ_per_txn']} pJ per "
                                f"{calibrated_dram['bytes_per_txn']} B transaction, but "
                                f"{CALIBRATED_DEVICE} gives {expected:.2f}")

    shipped_dram = {}
    for target in sorted(p.stem for p in pl.ACCELERATORS.glob("*.cfg")):
        declaration = dram_declaration(target)
        if declaration and declaration["device"] in dram_ref:
            shipped_dram[target] = declaration
    per_byte = {}
    for target, declaration in shipped_dram.items():
        if target == CALIBRATED:
            continue
        per_byte.setdefault(declaration["pJ_per_txn"]/declaration["bytes_per_txn"], set()).add(
            declaration["device"])
    device_independent = {cost: devices for cost, devices in per_byte.items() if len(devices) > 1}
    if not device_independent:
        failures.append("P4-8: no shipped DRAM energy is now shared across devices. Either the "
                        "configs became device-specific without this record being updated, or the "
                        "check stopped looking -- see the module docstring")
    spread = (max(float(r["read_pJ_per_byte"]) for r in dram_ref.values())
              / min(float(r["read_pJ_per_byte"]) for r in dram_ref.values()))
    if spread < 4.0:
        failures.append(f"P4-8: the referenced devices span only {spread:.2f}x per byte, so sharing "
                        f"one energy across them is no longer evidence of anything")

    # P4-9 -- the timing knobs ARE device-derived, which is what sharpens P4-8
    ras_declared = declared("gemmini_dram_detail", "dram", "t_ras_cycle")
    tras_tck = device_param(CALIBRATED_DEVICE, "tRAS")
    tck = device_param(CALIBRATED_DEVICE, "tCK")
    if ras_declared is None or tras_tck is None:
        failures.append("P4-9: cannot compare t_ras_cycle against the device file")
    else:
        expected_cycles = tras_tck*tck/MODEL_CLOCK_NS
        if abs(ras_declared[0] - expected_cycles) > 0.01:
            failures.append(f"P4-9: gemmini_dram_detail declares t_ras_cycle = {ras_declared[0]} but "
                            f"{CALIBRATED_DEVICE} gives {expected_cycles:.2f} ({tras_tck} tCK x "
                            f"{tck} ns / {MODEL_CLOCK_NS} ns). The DRAM timing was device-derived; "
                            f"if that is no longer true, P4-8's contrast loses its point")

    # P4-10 -- NVDLA calibrated fixture
    NVDLA = "nvdla_small_cacti22"
    cbuf = rows.get(("nvdla_cbuf_bank", NODE))
    cacc = rows.get(("nvdla_cacc_assembly", NODE))
    if cbuf is None or cacc is None:
        failures.append("P4-10: NVDLA reference rows missing from the CACTI CSV")
    else:
        rd, wr = float(cbuf["read_pJ_per_access"]), float(cbuf["write_pJ_per_access"])
        exp_read = [rd, 8*rd, rd]
        exp_write = [wr, 8*wr, wr]
        got_read = declared(NVDLA, "separate", "read_energy")
        got_write = declared(NVDLA, "separate", "write_energy")
        for slot, e, g in zip(SLOTS, exp_read, got_read or [None]*3):
            if g is None or abs(g - e) > 5e-4:
                failures.append(f"P4-10 separate.read_energy[{slot}]: {g} != CACTI-derived {e}")
        for slot, e, g in zip(SLOTS, exp_write, got_write or [None]*3):
            if g is None or abs(g - e) > 5e-4:
                failures.append(f"P4-10 separate.write_energy[{slot}]: {g} != CACTI-derived {e}")
        acc = declared(NVDLA, "spatial_arch", "accumulator_spill_energy")
        acc_bytes = float(cacc["line_bytes"])/2.0   # 128 b bus row consumed per byte: 16 B access
        exp_acc = (float(cacc["read_pJ_per_access"]) + float(cacc["write_pJ_per_access"]))/2.0/16.0
        if acc is None or abs(acc[2] - exp_acc) > 5e-3:
            failures.append(f"P4-10 accumulator_spill_energy[output]: "
                            f"{acc and acc[2]} != CACC-derived {exp_acc:.4f}")
        dram_row = 56.5312*8
        got_dram = declared(NVDLA, "dram", "read_energy")
        if got_dram is None or abs(got_dram[0] - dram_row) > 5e-2:
            failures.append(f"P4-10 dram.read_energy: {got_dram and got_dram[0]} != {dram_row}")
        # refusal + ESTIMATED on an actual result
        import glob as _glob
        nres = sorted(_glob.glob(str(HERE.parents[1]/"result"/NVDLA/"*"/"ws"/"layer_1.txt")))
        if not nres:
            failures.append("P4-10: no nvdla_small_cacti22 result to check the refusal on")
        else:
            text = open(nres[0]).read()
            if "Average power         : unsupported" not in text:
                failures.append("P4-10: the partially-calibrated NVDLA fixture was NOT refused a wattage")
            if "ESTIMATED" not in text:
                failures.append("P4-10: the NVDLA total is not marked ESTIMATED")
            if "PARTIAL cost (UNDERCOUNT)" not in text:
                failures.append("P4-10: the undercount is not visible on the component rows")

    if failures:
        for f in failures:
            print(f"FAIL {f}")
        print(f"{len(failures)} check(s) FAILED")
        return 1

    print(f"CACTI 7 reference: {len(rows)} rows, {len(components)} geometries x "
          f"{len({n for _, n in rows})} nodes  (validation/phase4/PROVENANCE.md)")
    print(f"{'geometry':>24} {'22nm read pJ':>13} {'22nm write pJ':>14} {'leak pJ/cycle':>14}")
    for component in components:
        row = rows[(component, NODE)]
        print(f"{component:>24} {float(row['read_pJ_per_access']):>13.4f} "
              f"{float(row['write_pJ_per_access']):>14.4f} "
              f"{float(row['leakage_mW'])*LEAK_PJ_PER_CYCLE:>14.4f}")
    print(f"P4-1 {CALIBRATED}'s SRAM costs are exactly the CACTI rows for its geometry ok")
    print(f"P4-2 {CALIBRATED} is geometrically consistent (equal size -> equal cost; "
          f"smaller never dearer) ok")
    print(f"P4-3 {SHIPPED}'s recorded inconsistency is still present ({len(shipped_violations)} "
          f"violation(s)) ok")
    for bad in shipped_violations:
        print(f"       {bad}")
    print(f"P4-4 {CALIBRATED} is refused a wattage for an UNDERCOUNTED numerator (its SRAM/DRAM "
          f"costs are external, its MAC/accumulator/cast/control are not); {SHIPPED} is refused for "
          f"having no declared unit at all ok")
    print("P4-5 the reference falls with the technology node and rises with array size ok")
    print(f"P4-6 {rederived} DDR device(s) re-derived from their own JEDEC parameters; the stacked "
          f"part is below every DDR part ok")
    print(f"P4-7 {CALIBRATED}'s DRAM energy is exactly {CALIBRATED_DEVICE}'s "
          f"{float(dram_ref[CALIBRATED_DEVICE]['read_pJ_per_byte']):.3f} pJ/byte x "
          f"{calibrated_dram['bytes_per_txn']} B ok")
    print(f"P4-8 the recorded device independence is still present: "
          f"{ {cost: sorted(devs) for cost, devs in device_independent.items()} } "
          f"over a {spread:.2f}x device spread ok")
    print(f"P4-9 t_ras_cycle = {ras_declared[0]} matches {CALIBRATED_DEVICE}'s "
          f"{tras_tck} tCK x {tck} ns / {MODEL_CLOCK_NS} ns -- the timing IS device-derived ok")
    print("P4-10 nvdla_small_cacti22: CBUF/CACC/DRAM costs equal their reference derivations; "
          "wattage refused, total ESTIMATED, undercount visible ok")
    print("NOT COVERED: NoP link energy has no external reference -- Simba is paywalled; "
          "PROVENANCE.md lists the figures that would close it")
    print("ALL PHASE 4 CHECKS PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
