#!/usr/bin/env bash
# Phase-8 (plan_sfu.md): run official nv_small SDP trace tests on the CRC-fixed
# EMULATION Verilator binary (see validation/nvdla/PROVENANCE.md for the RTL commit,
# toolchain and patches -- this reuses that exact environment).
#
# Usage: [NVDLA_PROJECT=nv_small] run_sdp_rtl_traces.sh <trace-name>...
# For each trace: build trace.bin via the stock trace-parser flow (verif/verilator
# Makefile recipe, reproduced verbatim), then run it in
# ext/nvdla/outdir/$NVDLA_PROJECT/verilator_emu/run_<trace>/run.log.
# Existing PASSing runs are kept (idempotent).
#
# Register-map python: the per-unit spec/manual .py files are generated by an ORDT
# post-processing perl step whose modules are unavailable on this machine, so projects
# without them fall back to nv_small's -- safe, because the CSB register ADDRESS MAP is
# config-invariant (same RDL; feature configs gate hardware, not addresses).
set -uo pipefail

NVDLA=/home/bogil/npusim/ext/nvdla
PROJECT=${NVDLA_PROJECT:-nv_small}
TRACES=$NVDLA/verif/tests/trace_tests/$PROJECT
TESTOUT=$NVDLA/outdir/$PROJECT/verilator/test
EMU=$NVDLA/outdir/$PROJECT/verilator_emu
VERIF=$NVDLA/verif/verilator
PYTHON=/usr/bin/python3
MANUAL=$NVDLA/outdir/$PROJECT/spec/manual
if [[ ! -f $MANUAL/NVDLA_SDP.py ]]; then
    MANUAL=$NVDLA/outdir/nv_small/spec/manual
fi

for t in "$@"; do
    if [[ -f $EMU/run_$t/run.log ]] && grep -q '\*\*\* PASS' "$EMU/run_$t/run.log"; then
        echo "KEEP  $t (already PASS)"
        continue
    fi
    if [[ ! -d $TRACES/$t ]]; then
        echo "SKIP  $t (no such trace)"
        continue
    fi
    if [[ ! -f $TESTOUT/$t/trace.bin ]]; then
        rm -rf "$TESTOUT/$t"
        mkdir -p "$TESTOUT/$t"
        ( cd "$TESTOUT/$t" && $PYTHON "$NVDLA/verif/tools/nvdla_trace_parser.py" \
              --file_path "$TRACES/$t/$t.cfg" ) >"$TESTOUT/$t/parse.log" 2>&1
        ( cd "$VERIF" && PYTHONPATH=$MANUAL \
              $PYTHON new_trace_to_verilator.py "$TESTOUT/$t/" "$TESTOUT/$t/trace.bin" ) \
              >>"$TESTOUT/$t/parse.log" 2>&1
        if [[ ! -f $TESTOUT/$t/trace.bin ]]; then
            echo "FAIL  $t (trace.bin build failed; see $TESTOUT/$t/parse.log)"
            continue
        fi
    fi
    mkdir -p "$EMU/run_$t"
    cp "$TESTOUT/$t/trace.bin" "$EMU/run_$t/"
    ( cd "$EMU/run_$t" && ../VNV_nvdla trace.bin >run.log 2>&1 )
    if grep -q '\*\*\* PASS' "$EMU/run_$t/run.log"; then
        echo "PASS  $t ($(grep -o 'done at [0-9]* ticks' "$EMU/run_$t/run.log"))"
    else
        echo "FAIL  $t ($(tail -1 "$EMU/run_$t/run.log"))"
    fi
done
